Amélioration de l'enrengistrement et l'affichage des chansons
TableauBits/Kalimba pull request #30
Opened 2022-04-12 18:48 UTC by rakruk

## Description

### :rocket: Nouveauté

### :tada: Quality of life
- La limite arbitraire de nombre de charactères pour le titre de la chanson et le nom de artiste à été augmenté à 100.
### :bug: Bugfix

### :hammer_and_wrench: Refactoring

## Dépendance issues/pull request

## Checklist

2022-04-12 23:17 UTC, Ithyx approved these changes, later dismissed
J'attends simplement que le code nécessaire soit merge sur Yatga pour merge ici, mais sinon c'est accepté

2022-04-18 02:46 UTC, Ithyx requested changes

2022-04-18 02:46 UTC, Ithyx commented on src/WebSocket/modules/constitution-manager.ts
> +const NAME_MAX_LENGTH = 100;
Pas besoin de changer la limite pour le nom de la constitution

2022-04-21 00:25 UTC, hvdbm commented on src/WebSocket/modules/constitution-manager.ts
> +const NAME_MAX_LENGTH = 100;
```suggestion
const NAME_MAX_LENGTH = 30;
```

2022-04-21 00:26 UTC, Ithyx approved these changes

2022-04-21 00:27 UTC, thehyouz commented
No hard feeling

2022-04-21 00:43 UTC, merged